### ISSUE TITLE
Failed generating certs:  open /etc/ssl/server/cert.pem: no such file or directory

### ISSUE THREAD

**Issue by Joshfindit** [PierreZ/goStatic#1]
`docker run -p 9001:8043 -v dist:/srv/http --name goStatic pierrezemb/gostatic`

```
2017/03/10 16:14:52 Starting goStatic
2017/03/10 16:14:52 Warning: generating self-signed certs, DO NOT USE IN PRODUCTION!
2017/03/10 16:14:55 Failed generating certs:  open /etc/ssl/server/cert.pem: no such file or directory
```

**Comment by PierreZ** [comment]
Thanks for the issue !

I must admit I wrote the code a long time ago, I'll have a look and fix it this week-end. 

I ditch goStatic in favor of this:

```bash
python -m SimpleHTTPServer
```

**Comment by Joshfindit** [comment]
Yeah, me too usually but I needed a quick http server as a docker container and yours came up near the top of the results for "docker static http server"

**Comment by PierreZ** [comment]
FYI, I'm rewriting goStatic @Joshfindit

**Comment by PierreZ** [comment]
Fixed the issue
