### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by explodecomputer** [PierreZ/goStatic#11]
The image builds fine and runs but exits immediately. docker logs gives:

```
❯ docker logs 3f55e51770b9
standard_init_linux.go:178: exec user process caused "exec format error"
```

Any idea what might be the issue?

Thanks

**Comment by guyathomas** [comment]
Are you trying to run this on a device with a different architecture? i.e ARM on a Raspberry Pi?

**Comment by PierreZ** [comment]
Hello! 

I think (like @guythomas), you are trying to run a binary built for another platform that the one you are running.

If so, you can easily add GOOS and GOARCH env variables before running go generate to cross-compile

**Comment by explodecomputer** [comment]
Hi both, thanks very much for responding. I was trying to run it on rpi, not sure what I was thinking to not check architecture of the binaries. Will do this, thanks again.
