### ISSUE TITLE
Base image centurylink/ca-certs is outdated (3 years old)

### ISSUE THREAD

**Issue by dolmen** [PierreZ/goStatic#16]
The base image [`centurylink/ca-certs`](https://github.com/CenturyLinkLabs/ca-certs-base-image) has not been updated since 3 years ago. It contains certificates that have been removed from browser because not trustable. It also probably includes expired certificates, and lack modern root certificates.

**Comment by barmic** [comment]
I think you could use one of  methods:

- get cert from golang image. It contains a `/etc/ssl/certs/ca-certificates.crt`. But I don't know if this images is production ready
- use gcr.io/distroless/base this is a bit too big for you but is a production ready image
- create a new step for your build with distroless to copy the file in your final image

**Comment by furyfire** [comment]
Is there really  a need for root certifcates? why not simply build ontop of the scratch image and provide a small container?

**Comment by PierreZ** [comment]
Back from holidays, I will have a look soon on what is available and what we can do about it 👍

**Comment by PierreZ** [comment]
Just pushed a branch that should be working, if you want to test it :wink:

**Comment by w3st3ry** [comment]
@PierreZ Tested now. Works like a charm.

**Comment by PierreZ** [comment]
In progress 👍

**Comment by w3st3ry** [comment]
@PierreZ thanks 💃
