### ISSUE TITLE
gzip support?

### ISSUE THREAD

**Issue by hayond** [PierreZ/goStatic#20]
i love this small static server，use for my frontend project，i generate index.js and index.js.gz，but on my browser，it default read  index.js.  can easily add gzip support without increase docker image size?

**Comment by PierreZ** [comment]
Hi @hayond,

I think that could be implemented pretty easily, backporting [this code](https://gist.github.com/CJEnright/bc2d8b8dc0c1389a9feeddb110f822d7). Do you want to contribute to goStatic? :rocket:

**Comment by hayond** [comment]
oh,  i am a beginner of go language, but let me have a try  :)

**Comment by PierreZ** [comment]
Awesome @hayond, let me know if you have any questions, or if you need help :smiley:

**Comment by dimitor115** [comment]
@PierreZ I have also tried, please take a look at my PR :smile:

**Comment by PierreZ** [comment]
Thanks a lot @dimitor115, closing the issue :+1:
