### ISSUE TITLE
Updated Docker hub image

### ISSUE THREAD

**Issue by nigelsim** [PierreZ/goStatic#26]
Hi, I note that the image at [Docker hub](https://hub.docker.com/r/pierrezemb/gostatic/) is from 9 months ago. Do you plan on pushing a new image in the near future?

**Comment by PierreZ** [comment]
Hello @nigelsim !

Thanks to you, I discovered that the integration with Docker Hub was broken. Just pushed a [new version according to master](https://hub.docker.com/r/pierrezemb/gostatic/tags).

Thanks again!
