### ISSUE TITLE
Docker Hub ARM image

### ISSUE THREAD

**Issue by antoniofagardo** [PierreZ/goStatic#31]
Hi, I noted that the image at Docker hub is only built for linux/amd64. Do you plan on pushing a new image for ARM in the near future?

Would be wonderful to be able to use this image on our small raspberry pi :)

I'm not sure how what's your process to push the image to docker-hub but I only had to change the `GOARCH` parameter to `GOARCH=arm` in the `RUN` command in the stage 0 of the Dockerfile to generate it locally on my pi

**Comment by PierreZ** [comment]
Hi @antoniofagardo !

Thanks for your proposal, yes it would be wonderful 🌈 

Are you interested into contributing to goStatic? If so, you can (for example) create a PR with a new `Dockerfile.arm` and I will setup the automated build on the Hub 😉 

If I remember correctly, depending on the rapsberry pi's version, the target is not the same(`GOARM=6` vs `GOARM=7`).

We may create multiple dockerfiles for now, as we cannot easily build multiples images on automated build from DockerHub. We should move on to github actions at some point to ease that part, but for now, multiple files are fine and easy to maintain 😄 

Please let me know if you are interested in this 🚀

**Comment by antoniofagardo** [comment]
I'll be happy to contribute, I'll open a PR shortly and follow your suggestion for adding new dockerfile 😉 

To cover the full range of raspberry pi (1, 2, 3, 4, 0, 0w), I believe we will need the following GOOS/GOARCH/[GOARM]:

-  linux/arm/5

- linux/arm/6

- linux/arm/7

- linux/arm64

I'll create a Dockerfile for each target and submit it for your review

**Comment by antoniofagardo** [comment]
Opened PR #32

**Comment by PierreZ** [comment]
PR #32 is merged! Waiting for DockerHub to build images...

**Comment by antoniofagardo** [comment]
Just pulled the `latest-arm7` from docker hub to test on my pi3 and it's working like a charm!
If all is good on your side, I think we can close this issue

**Comment by PierreZ** [comment]
Thanks again for your contribution and tests!
