### ISSUE TITLE
Add a flag to disable directory listing

### ISSUE THREAD

**Issue by obilodeau** [PierreZ/goStatic#5]
There should be a way to disable directory listing. It can reveal files that shouldn't be visible.

As a work-around, I know I can put empty `index.html` files in every directories but it is not convenient for large file trees.

**Comment by PierreZ** [comment]
[It seems easy to implement](https://groups.google.com/forum/#!topic/golang-nuts/bStLPdIVM6w), it could be an easy flag. Do you want to do the PR? 👍

**Comment by obilodeau** [comment]
Cool to know but no. I've switched to an nginx-alpine container instead and my workshop is now over.

**Comment by dudeskeeroo** [comment]
I mentioned this on another issue, but Google takes us here too. Here's a workaround:

Create an `index.html` file in the directory that you want to disable listings in I've created an empty one and now file listings don't occur.
