### ISSUE TITLE
Fallback not working at least for me...

### ISSUE THREAD

**Issue by alexandre-dos-reis** [PierreZ/goStatic#55]
Hello there,

I have an Angular SPA app with 3 routes setup like this : 

- `/` -> this one is working on reload and through navigation.
- `/another-route-1` -> this one is working only through navigation.
- `/another-route-2` -> this one is working only through navigation.

I have only one `index.html`. I think this is caused by the fallback not working properly.

Here's my dockerfile : 

```dockefile
FROM pierrezemb/gostatic:latest as frontend
COPY --from=builder /app/dist/apps/frontend /srv/http
EXPOSE 8043
CMD ["goStatic", "--fallback", "index.html"]
```

I also tried without the option but none are working.

Thank you for your help.

**Comment by michaelstokes93** [comment]
Hi @alexandre-dos-reis 

I had the same question. 

**Reviewing the arguments over at:**
https://hub.docker.com/r/pierrezemb/gostatic/
https://github.com/PierreZ/goStatic

shows us that we can use `-fallback`

**In my case, I just have the following of which works:**

```
FROM pierrezemb/gostatic
CMD [ "-fallback", "index.html" ]
COPY ./dist/apps/geoaudit/ /srv/http/
```

**And from the terminal I see when running:**

Preparing to run: `/goStatic -fallback index.html` as appuser

**Try changing** 

`--fallback` to `-fallback` or removing the first element "goStatic" and just having ["-fallback", "index.html"].

**Comment by alexandre-dos-reis** [comment]
Hi @mahalowolf,

Will try that asap.

Thank you.

**Comment by alexandre-dos-reis** [comment]
@mahalowolf  Thank you very much, this indeed works for me.

For anyone searching the same result : 

- If you're running a SPA : 

```dockerfile
FROM pierrezemb/gostatic:latest
COPY ./your/dist/folder /srv/http
EXPOSE 8043
CMD [ "-fallback", "index.html" ]
```

- If you're running static html pages and want to provide a 404 page to the user : 

```dockerfile
FROM pierrezemb/gostatic:latest
COPY ./your/dist/folder /srv/http
EXPOSE 8043
CMD [ "-fallback", "404.html" ]
```
