### ISSUE TITLE
 http basic auth never prompts or allows a login

### ISSUE THREAD

**Issue by extremeshok** [PierreZ/goStatic#9]
example

docker stop goStatic && docker rm goStatic && docker run -d -p 8088:8043 -v /backup/www:/srv/http --name goStatic pierrezemb/gostatic -enable-basic-auth -set-basic-auth "user:pass"

http://user:pass@docker.example.com:8088/

results in authorization failed

**Comment by PierreZ** [comment]
Bad copy/paste between computers, sorry about that :tongue:. Should be fixed

**Comment by extremeshok** [comment]
@PierreZ 

Confirmed working, thanks for the prompt fix.

````
$ echo "working" > /backup/www/index.html
$ curl gopher:A6A487691F79F0CF65FF867A5F62933D@127.0.0.1:8088
working
````
